// inspect 結果（実在の artboard / state machine / input 名）から統合コードを生成する
import type { InspectResult } from "./riveHost.js";

export type Framework = "react" | "js" | "vue" | "svelte" | "flutter";

export function generateCode(
  framework: Framework,
  fileName: string,
  info: InspectResult
): string {
  const ab = info.artboards[0];
  if (!ab) return "// この .riv ファイルにはアートボードがありません";
  const sm = ab.stateMachines[0];
  const inputsDoc = sm
    ? sm.inputs.map((i) => ` *  - ${i.name} (${i.type}, initial: ${i.value})`).join("\n")
    : " *  (state machine なし)";
  const header = `/**
 * Generated by rive-mcp for ${fileName}
 * Artboard: ${ab.name} (${Math.round(ab.width)}x${Math.round(ab.height)})
 * State Machine: ${sm ? sm.name : "-"}
 * Inputs:
${inputsDoc}
 */`;

  switch (framework) {
    case "react":
      return `${header}
import { useRive, useStateMachineInput } from "@rive-app/react-canvas";

export default function RiveAnimation() {
  const { rive, RiveComponent } = useRive({
    src: "/${fileName}",
    artboard: "${ab.name}",${sm ? `\n    stateMachines: "${sm.name}",` : ""}
    autoplay: true,
  });
${
  sm
    ? sm.inputs
        .map(
          (i) =>
            `  const ${toIdent(i.name)}Input = useStateMachineInput(rive, "${sm.name}", "${i.name}");`
        )
        .join("\n")
    : ""
}

  return <RiveComponent style={{ width: ${Math.round(ab.width)}, height: ${Math.round(ab.height)} }} />;
}`;

    case "js":
      return `${header}
import { Rive } from "@rive-app/canvas";

const rive = new Rive({
  src: "/${fileName}",
  canvas: document.getElementById("canvas"),
  artboard: "${ab.name}",${sm ? `\n  stateMachines: "${sm.name}",` : ""}
  autoplay: true,
  onLoad: () => {
    rive.resizeDrawingSurfaceToCanvas();${
      sm
        ? `\n    const inputs = rive.stateMachineInputs("${sm.name}");${sm.inputs
            .map(
              (i) =>
                `\n    const ${toIdent(i.name)} = inputs.find((x) => x.name === "${i.name}"); // ${i.type}`
            )
            .join("")}`
        : ""
    }
  },
});`;

    case "vue":
      return `${header}
<script setup>
import { onMounted, onUnmounted, ref } from "vue";
import { Rive } from "@rive-app/canvas";

const canvas = ref(null);
let rive = null;

onMounted(() => {
  rive = new Rive({
    src: "/${fileName}",
    canvas: canvas.value,
    artboard: "${ab.name}",${sm ? `\n    stateMachines: "${sm.name}",` : ""}
    autoplay: true,
    onLoad: () => rive.resizeDrawingSurfaceToCanvas(),
  });
});
onUnmounted(() => rive?.cleanup());
</script>

<template>
  <canvas ref="canvas" width="${Math.round(ab.width)}" height="${Math.round(ab.height)}"></canvas>
</template>`;

    case "svelte":
      return `${header}
<script>
  import { onMount, onDestroy } from "svelte";
  import { Rive } from "@rive-app/canvas";

  let canvas;
  let rive;

  onMount(() => {
    rive = new Rive({
      src: "/${fileName}",
      canvas,
      artboard: "${ab.name}",${sm ? `\n      stateMachines: "${sm.name}",` : ""}
      autoplay: true,
      onLoad: () => rive.resizeDrawingSurfaceToCanvas(),
    });
  });
  onDestroy(() => rive?.cleanup());
</script>

<canvas bind:this={canvas} width="${Math.round(ab.width)}" height="${Math.round(ab.height)}"></canvas>`;

    case "flutter":
      return `${header.replace(/^\/\*\*|\*\/$/g, "").split("\n").map((l) => "// " + l.replace(/^ \* ?/, "")).join("\n")}
import 'package:flutter/material.dart';
import 'package:rive/rive.dart';

class RiveAnimationWidget extends StatefulWidget {
  const RiveAnimationWidget({super.key});

  @override
  State<RiveAnimationWidget> createState() => _RiveAnimationWidgetState();
}

class _RiveAnimationWidgetState extends State<RiveAnimationWidget> {
${sm ? sm.inputs.map((i) => flutterInputField(i)).join("\n") : ""}

  void _onInit(Artboard artboard) {${
    sm
      ? `
    final controller = StateMachineController.fromArtboard(artboard, '${sm.name}');
    if (controller == null) return;
    artboard.addController(controller);${sm.inputs
      .map((i) => flutterInputInit(i))
      .join("")}`
      : ""
  }
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: ${Math.round(ab.width)},
      height: ${Math.round(ab.height)},
      child: RiveAnimation.asset(
        'assets/${fileName}',
        artboard: '${ab.name}',
        onInit: _onInit,
      ),
    );
  }
}`;
  }
}

function toIdent(name: string): string {
  const cleaned = name.replace(/[^a-zA-Z0-9_$]/g, "_");
  return /^[0-9]/.test(cleaned) ? "_" + cleaned : cleaned;
}

function flutterInputField(i: { name: string; type: string }): string {
  const t = i.type === "number" ? "SMINumber" : i.type === "boolean" ? "SMIBool" : "SMITrigger";
  return `  ${t}? ${toIdent(i.name)};`;
}

function flutterInputInit(i: { name: string; type: string }): string {
  const cast = i.type === "number" ? "SMINumber" : i.type === "boolean" ? "SMIBool" : "SMITrigger";
  return `\n    ${toIdent(i.name)} = controller.findInput<${
    i.type === "number" ? "double" : "bool"
  }>('${i.name}') as ${cast}?;`;
}
